Repository lc-tut/club-portal-frontend, pull requests merged in 2021-12, with the labels that each got.

#104 Top ページのリファクタリング
  src/components/common/Button/MenuButton.tsx
  src/components/common/Button/PortalButton.tsx
  src/components/common/Button/index.tsx
  src/components/common/PortalButton.tsx
  src/pages/top.tsx
  src/types/button.ts
Labels: enhancement

#112 @svgr/webpack に起因するバグを修正
  src/components/common/DefaultUserIcon.tsx
  src/components/common/Logo.tsx
  src/types/svg.d.ts
  webpack.config.ts
Labels: bug

#130 px指定をrem/em指定に変更
  src/components/common/Button/MenuButton.tsx
  src/components/common/Button/PortalButton.tsx
  src/components/common/Button/index.tsx
  src/components/global/Footer.tsx
  src/components/global/Header.tsx
  src/pages/top.tsx
Labels: fix

#141 Storybook の Story を更新
  .eslintrc
  .gitignore
  .storybook/main.js
  src/components/common/Button/MenuButton.stories.tsx
  src/components/common/Button/PortalButton.stories.tsx
  src/components/common/Icon/DefaultUserIcon.stories.tsx
  src/components/common/Icon/DefaultUserIcon.tsx
  src/components/common/Icon/Logo.stories.tsx
  src/components/common/Icon/Logo.tsx
  src/components/common/Icon/index.ts
  src/components/global/Footer.tsx
  src/components/global/Header.tsx
  src/pages/top.tsx
Labels: enhancement
